import "@/app/globals.css";
import styles from "@/styles/layout/layout.module.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={styles.html}>
      <body>{children}</body>
    </html>
  )
}
